# Generated by Django 4.2.1 on 2023-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
