# Generated by Django 4.2.1 on 2023-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscribers_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscriber',
        ),
    ]
